Upgrading to Nuke 6
OctopusDeploy/NukeBuildComponents pull request #8
Opened 2022-04-06 02:10 UTC by slewis74

2022-04-06 03:15 UTC, cailyoung requested changes
Hey there! Thanks for the contribution. Please consider putting some context in the PR description as to why the bump is happening so that we can consider impacts.

You may want to also include a bump to the .NET version specified in the workflow file for `setup-dotnet`; I _think_ Nuke can deal with it, but if we're going to bother with `setup-dotnet` let's have the versions match.

2022-04-06 03:15 UTC, cailyoung commented on source/NukeBuildComponents/IOctopusNukeBuild.cs
> +        [OctoVersion] OctoVersionInfo? OctoVersionInfo => TryGetValue(() => OctoVersionInfo);
I think that making this nullable might be causing `IPackComponent` to set empty string outputs for `semver` and `prerelease_tag`, which is causing GHA to fail on the tag action (and that seems to have pushed a `v1.0.0` for some reason...)

2022-04-06 03:15 UTC, cailyoung commented on source/NukeBuildComponents/IOctopusNukeBuild.cs
> +        [OctoVersion] OctoVersionInfo? OctoVersionInfo => TryGetValue(() => OctoVersionInfo);
Yeah, see [here](https://github.com/OctopusDeploy/NukeBuildComponents/runs/5843967911?check_suite_focus=true#step:4:139) - `null` in the output.

2022-04-07 06:25 UTC, matt-richardson approved these changes
I think we can fix up those nullability things - we want to go :boom: if things are null instead of going 🙈 .

I'm not enthused about the horrible solution that I've contributed, but it gets us out of the hole for now.
I've reached out to Mattias (nuke maintainer) about it, he's going to look into a better fix at source. Once that happens we can revert this (I don't want this code to live on forever).

2022-04-07 06:25 UTC, matt-richardson commented on source/NukeBuildComponents/ICompile.cs
> +                    .SetVersion(OctoVersionInfo?.FullSemVer)
```suggestion
                    .SetVersion(OctoVersionInfo!.FullSemVer)
```

2022-04-07 06:25 UTC, matt-richardson commented on source/NukeBuildComponents/ICleanCode.cs
> +                    .SetTargetPath(Solution?.Path));
Nearly all these should be `!` (can we fix it at source?)

2022-04-07 06:25 UTC, matt-richardson commented on source/NukeBuildComponents/IPackComponent.cs
> +                DotNetPack(c => c
nuke convention is `_` here

2022-04-07 06:25 UTC, matt-richardson commented on source/NukeBuildComponents/IOctopusNukeBuild.cs
> +        // we need this custom method instead of the "normal" TryGetValue,
Important note here

2022-04-07 06:25 UTC, matt-richardson commented on source/NukeBuildComponents/OctoVersionThatWorksWithBuildComponentsAttribute.cs
> +        //Note: this is the only real change we need here:
Important note here

2022-04-08 00:53 UTC, merged